export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";

export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";

export const ADD_TO_WATCHED_FAIL = "ADD_TO_WATCHED_FAIL";
export const ADD_TO_WATCHED_SUCCESS = "ADD_TO_WATCHED_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
